### ISSUE TITLE
The latest version of Chrome no longer works in v20

### ISSUE THREAD

**Issue by fontoms** [Zastinian/eseggs#1]
```
Error: Failed to launch the browser process! spawn /home/container/.cache/puppeteer/chrome/linux-127.0.6533.88/chrome-linux64/chrome ENOENT


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/home/container/node_modules/@puppeteer/browsers/lib/cjs/launch.js:310:24)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

I think this is due to an update in https://github.com/Zastinian/esdock

**Comment by sirlupusdev** [comment]
I'm experiencing the same issue, are you aware of any workarounds as of now?

**Comment by Zastinian** [comment]
Let me check

**Comment by Zastinian** [comment]
It should be fixed by now! @fontoms @sirlupusdev 😁

**Comment by sirlupusdev** [comment]
Thank you! It does report "No usable sandbox" - is it necessary to disable that or is there some way to preserve it?

**Comment by Zastinian** [comment]
It should be disabled because sandbox is to open a web in window which pterodactyl does not support @sirlupusdev

**Comment by sirlupusdev** [comment]
Alright, thank you - the docs simply stated that it "significantly decreases security" and my first thought was eeh, maybe ask first.
